# Generated by Django 3.2.5 on 2022-02-07 11:05

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('bank', models.BooleanField(default=False)),
                ('customer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_type', models.CharField(choices=[('ALL', 'ALL'), ('APF', 'APF'), ('RF', 'RF'), ('DF', 'DF')], default='*', max_length=10)),
                ('finance_request_type', models.CharField(choices=[('AUTOMATIC', 'AUTOMATIC'), ('ON_REQUEST', 'ON_REQUEST')], default=None, max_length=15)),
                ('limit_currency', models.CharField(max_length=3)),
                ('total_limit_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('finance_currency', models.CharField(max_length=3)),
                ('settlement_currency', models.CharField(max_length=3)),
                ('expiry_date', models.DateField(default=datetime.date.today)),
                ('max_finance_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_invoice_age_for_funding', models.IntegerField()),
                ('max_age_for_repayment', models.IntegerField()),
                ('minimum_period', models.IntegerField()),
                ('maximum_period', models.IntegerField()),
                ('maximum_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('minimum_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('financed_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grace_period', models.IntegerField()),
                ('interest_type', models.CharField(choices=[('FIXED', 'FIXED'), ('FLOATING', 'FLOATING')], default=None, max_length=15)),
                ('interest_rate_type', models.CharField(choices=[('LIBOR', 'LIBOR'), ('EURIBOR', 'EURIBOR'), ('SOFOR', 'SOFOR')], default=None, max_length=15)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('margin', models.DecimalField(decimal_places=2, max_digits=5)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.parties')),
            ],
        ),
        migrations.CreateModel(
            name='submodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=35)),
                ('api_route', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Transitionpartytype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='workflowitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('stage', models.CharField(choices=[('DRAFT', 'DRAFT'), ('AWAITING_APPROVAL', 'AWAITING_APPROVAL'), ('AWAITING_ACCEPTANCE', 'AWAITING_ACCEPTANCE'), ('ACCEPTED', 'ACCEPTED'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('FINANCE_REQUESTED', 'FINANCE_REQUESTED'), ('FINANCED', 'FINANCED'), ('FINANCE_REJECTED', 'FINANCE_REJECTED'), ('SETTLED', 'SETTLED'), ('OVERDUE', 'OVERDUE'), ('AWAITING_SIGN_A', 'AWAITING_SIGN_A'), ('AWAITING_SIGN_B', 'AWAITING_SIGN_B'), ('AWAITING_SIGN_C', 'AWAITING_SIGN_C'), ('DELETED', 'DELETED')], max_length=255)),
                ('initial_state', models.CharField(default='DRAFT', max_length=50)),
                ('interim_state', models.CharField(default='DRAFT', max_length=50)),
                ('final_state', models.CharField(default='DRAFT', max_length=50)),
                ('next_available_transitions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500, null=True), blank=True, null=True, size=None)),
                ('action', models.CharField(default='SAVE', max_length=25)),
                ('current_from_party', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_party', to='accounts.parties')),
                ('current_to_party', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_party', to='accounts.parties')),
                ('event_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customername', to=settings.AUTH_USER_MODEL)),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transaction.programs')),
            ],
        ),
        migrations.CreateModel(
            name='workevents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(default='DRAFT', max_length=50)),
                ('to_state', models.CharField(default='DRAFT', max_length=50)),
                ('interim_state', models.CharField(default='DRAFT', max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('from_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_we_party', to='accounts.parties')),
                ('to_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_wf_party', to='accounts.parties')),
                ('workitems', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflowevent', to='transaction.workflowitems')),
            ],
        ),
        migrations.CreateModel(
            name='Pairings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finance_request', models.CharField(choices=[('AUTOMATIC', 'AUTOMATIC'), ('ON_REQUEST', 'ON_REQUEST')], default=None, max_length=15)),
                ('total_limit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('expiry_date', models.DateField(default=datetime.date.today)),
                ('max_finance_percentage', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_invoice_age_for_funding', models.IntegerField()),
                ('max_age_for_repayment', models.IntegerField()),
                ('minimum_period', models.IntegerField()),
                ('maximum_period', models.IntegerField()),
                ('minimum_amount_currency', models.CharField(max_length=3)),
                ('minimum_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('maximum_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('financed_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('grace_period', models.IntegerField()),
                ('interest_type', models.CharField(choices=[('FIXED', 'FIXED'), ('FLOATING', 'FLOATING')], default=None, max_length=15)),
                ('interest_rate_type', models.CharField(choices=[('LIBOR', 'LIBOR'), ('EURIBOR', 'EURIBOR'), ('SOFOR', 'SOFOR')], default=None, max_length=15)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('margin', models.DecimalField(decimal_places=2, max_digits=8)),
                ('counterparty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.parties')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pairingscurrency', to='accounts.currencies')),
                ('finance_currency_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='financedcurrency', to='accounts.currencies')),
                ('program_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transaction.programs')),
                ('settlement_currency_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.currencies')),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, max_length=10, null=True)),
                ('issue_date', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField(default=datetime.date.today)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('funding_req_type', models.CharField(choices=[('AUTOMATIC', 'AUTOMATIC'), ('ON_REQUEST', 'ON_REQUEST')], default=None, max_length=15)),
                ('interest_rate', models.DecimalField(decimal_places=1, max_digits=6)),
                ('financed_amount', models.DecimalField(decimal_places=1, max_digits=6)),
                ('bank_load_id', models.CharField(max_length=55)),
                ('finance_currency_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='financedinvoicecurrency', to='accounts.currencies')),
                ('invoice_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoicecurrencytype', to='accounts.currencies')),
                ('pairing', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transaction.pairings')),
                ('settlement_currency_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.currencies')),
                ('wf_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.workflowitems')),
            ],
        ),
        migrations.CreateModel(
            name='invoice_uploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_type', models.CharField(choices=[('*', '*'), ('APF', 'APF'), ('RF', 'RF'), ('DF', 'DF')], default='*', max_length=15)),
                ('invoices', models.JSONField()),
                ('wf_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.workflowitems')),
            ],
        ),
        migrations.CreateModel(
            name='FundingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField()),
                ('financed_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('due_date', models.DateField(default=datetime.date.today)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.programs')),
            ],
        ),
    ]
