# Generated by Django 3.2.5 on 2021-12-23 12:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('bank', models.BooleanField(default=False)),
                ('customer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Financerequesttype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Interestratetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='interesttype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='submodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=35)),
                ('api_route', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Transitionpartytype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_currency', models.CharField(max_length=3)),
                ('total_limit_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('finance_currency', models.CharField(max_length=3)),
                ('settlement_currency', models.CharField(max_length=3)),
                ('expiry_date', models.DateField(default=datetime.date.today)),
                ('max_finance_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_invoice_age_for_funding', models.IntegerField()),
                ('max_age_for_repayment', models.IntegerField()),
                ('minimum_period', models.IntegerField()),
                ('maximum_period', models.IntegerField()),
                ('maximum_amount', models.CharField(max_length=3)),
                ('minimum_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('financed_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grace_period', models.IntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('margin', models.DecimalField(decimal_places=2, max_digits=5)),
                ('finance_request_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transaction.financerequesttype')),
                ('interest_rate_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.interestratetype')),
                ('interest_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.interesttype')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.parties')),
                ('program_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transaction.programtype')),
                ('wf_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.workflowitems')),
            ],
        ),
        migrations.CreateModel(
            name='Pairings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_limit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('expiry_date', models.DateField(default=datetime.date.today)),
                ('max_finance_percentage', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_invoice_age_for_funding', models.IntegerField()),
                ('max_age_for_repayment', models.IntegerField()),
                ('minimum_period', models.IntegerField()),
                ('maximum_period', models.IntegerField()),
                ('minimum_amount_currency', models.CharField(max_length=3)),
                ('minimum_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('maximum_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('financed_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('grace_period', models.IntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('margin', models.DecimalField(decimal_places=2, max_digits=8)),
                ('counterparty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.parties')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pairingscurrency', to='accounts.currencies')),
                ('finance_currency_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='financedcurrency', to='accounts.currencies')),
                ('finance_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.financerequesttype')),
                ('interest_rate_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transaction.interestratetype')),
                ('interest_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transaction.interesttype')),
                ('program_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transaction.programs')),
                ('settlement_currency_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.currencies')),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, max_length=10, null=True)),
                ('issue_date', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField(default=datetime.date.today)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('interest_rate', models.DecimalField(decimal_places=1, max_digits=6)),
                ('financed_amount', models.DecimalField(decimal_places=1, max_digits=6)),
                ('bank_load_id', models.CharField(max_length=55)),
                ('finance_currency_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='financedinvoicecurrency', to='accounts.currencies')),
                ('funding_req_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='transaction.financerequesttype')),
                ('invoice_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoicecurrencytype', to='accounts.currencies')),
                ('pairing', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transaction.pairings')),
                ('settlement_currency_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.currencies')),
                ('wf_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.workflowitems')),
            ],
        ),
        migrations.CreateModel(
            name='invoice_uploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoices', models.JSONField()),
                ('program_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.programtype')),
                ('wf_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.workflowitems')),
            ],
        ),
        migrations.CreateModel(
            name='FundingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField()),
                ('financed_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('due_date', models.DateField(default=datetime.date.today)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.programs')),
            ],
        ),
    ]
