# Generated by Django 3.2.5 on 2021-12-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoices',
            old_name='funding_req_type',
            new_name='finance_req_type',
        ),
        migrations.RenameField(
            model_name='invoices',
            old_name='wf_item_id',
            new_name='wf_item',
        ),
        migrations.RenameField(
            model_name='pairings',
            old_name='counterparty_id',
            new_name='counterparty',
        ),
        migrations.RenameField(
            model_name='programs',
            old_name='wf_item_id',
            new_name='wf_item',
        ),
        migrations.AlterField(
            model_name='invoice_uploads',
            name='program_type',
            field=models.CharField(choices=[('ALL', 'ALL'), ('APF', 'APF'), ('RF', 'RF'), ('DF', 'DF')], default='ALL', max_length=15),
        ),
        migrations.AlterField(
            model_name='programs',
            name='program_type',
            field=models.CharField(choices=[('ALL', 'ALL'), ('APF', 'APF'), ('RF', 'RF'), ('DF', 'DF')], default='ALL', max_length=10),
        ),
        migrations.DeleteModel(
            name='ProgramType',
        ),
    ]
