# Generated by Django 3.2.5 on 2022-05-18 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20220517_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workevents',
            name='record_datas',
        ),
    ]
