# Generated by Django 3.2.5 on 2022-02-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_rename_bank_load_id_invoices_bank_loan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowitems',
            name='final',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
