# Generated by Django 3.2.5 on 2022-03-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_pairings_counterparty_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workevents',
            name='b_final',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='workevents',
            name='s_final',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
