# Generated by Django 3.2.5 on 2021-12-29 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20211227_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programs',
            name='wf_item',
        ),
    ]
