# Generated by Django 3.2.5 on 2022-05-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_remove_workevents_record_datas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundingrequest',
            options={'verbose_name_plural': 'FundingRequest'},
        ),
        migrations.AlterModelOptions(
            name='invoices',
            options={'verbose_name_plural': 'Invoice'},
        ),
        migrations.AlterModelOptions(
            name='invoiceuploads',
            options={'verbose_name_plural': 'Invoiceupload'},
        ),
        migrations.AlterModelOptions(
            name='pairings',
            options={'verbose_name_plural': 'Pairing'},
        ),
        migrations.AlterModelOptions(
            name='programs',
            options={'verbose_name_plural': 'Program'},
        ),
        migrations.AlterModelOptions(
            name='transitionpartytype',
            options={'verbose_name_plural': 'Transitionpartytype'},
        ),
        migrations.AlterModelOptions(
            name='workevents',
            options={'verbose_name_plural': 'WorkEvent'},
        ),
        migrations.AlterModelOptions(
            name='workflowitems',
            options={'verbose_name_plural': 'Workflowitem'},
        ),
        migrations.AddField(
            model_name='workevents',
            name='record_datas',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
