# Generated by Django 3.2.5 on 2022-03-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20220325_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowitems',
            name='flow_field',
            field=models.CharField(default='DRAFT', max_length=255),
        ),
    ]
