# Generated by Django 3.2.5 on 2022-02-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_workflowitems_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowitems',
            name='subaction',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
