# Generated by Django 3.2.5 on 2022-02-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_workflowitems_subaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowitems',
            name='final',
        ),
        migrations.AddField(
            model_name='workevents',
            name='final',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
