# Generated by Django 3.2.5 on 2022-05-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_alter_workevents_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workevents',
            name='record_datas',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
