# Generated by Django 3.2.5 on 2022-05-23 11:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_alter_workevents_record_datas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workevents',
            name='record_datas',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
