# Generated by Django 3.2.5 on 2022-02-12 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220211_2236'),
        ('transaction', '0007_alter_workflowitems_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='wf_item_id',
        ),
        migrations.AddField(
            model_name='invoices',
            name='party',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.parties'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workflowitems',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.invoices'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='financed_amount',
            field=models.DecimalField(decimal_places=1, max_digits=8),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='interest_rate',
            field=models.DecimalField(decimal_places=1, max_digits=8),
        ),
        migrations.AlterField(
            model_name='workflowitems',
            name='program',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.programs'),
        ),
        migrations.AlterField(
            model_name='workflowitems',
            name='stage',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('AWAITING_APPROVAL', 'AWAITING_APPROVAL'), ('AWAITING_ACCEPTANCE', 'AWAITING_ACCEPTANCE'), ('ACCEPTED', 'ACCEPTED'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('FINANCE_REQUESTED', 'FINANCE_REQUESTED'), ('FINANCED', 'FINANCED'), ('FINANCE_REJECTED', 'FINANCE_REJECTED'), ('SETTLED', 'SETTLED'), ('OVERDUE', 'OVERDUE'), ('AWAITING_SIGN_A', 'AWAITING_SIGN_A'), ('AWAITING_SIGN_B', 'AWAITING_SIGN_B'), ('AWAITING_SIGN_C', 'AWAITING_SIGN_C'), ('DELETED', 'DELETED'), ('SIGN_A', 'SIGN_A'), ('SIGN_B', 'SIGN_B'), ('SIGN_C', 'SIGN_C'), ('SUBMIT', 'SUBMIT'), ('MAKER', 'MAKER'), ('NONE', 'NONE')], max_length=255),
        ),
    ]
