# Generated by Django 3.2.5 on 2022-02-14 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_auto_20220212_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='workevents',
            name='c_final',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='workflowitems',
            name='stage',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('AWAITING_APPROVAL', 'AWAITING_APPROVAL'), ('AWAITING_ACCEPTANCE', 'AWAITING_ACCEPTANCE'), ('ACCEPTED', 'ACCEPTED'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('FINANCE_REQUESTED', 'FINANCE_REQUESTED'), ('FINANCED', 'FINANCED'), ('FINANCE_REJECTED', 'FINANCE_REJECTED'), ('SETTLED', 'SETTLED'), ('OVERDUE', 'OVERDUE'), ('AWAITING_SIGN_A', 'AWAITING_SIGN_A'), ('AWAITING_SIGN_B', 'AWAITING_SIGN_B'), ('AWAITING_SIGN_C', 'AWAITING_SIGN_C'), ('DELETED', 'DELETED'), ('SIGN_A', 'SIGN_A'), ('SIGN_B', 'SIGN_B'), ('SIGN_C', 'SIGN_C'), ('SUBMIT', 'SUBMIT'), ('MAKER', 'MAKER'), ('NONE', 'NONE'), ('INITIAL_STATE', 'INITIAL_STATE')], max_length=255),
        ),
    ]
