# Generated by Django 3.2.5 on 2022-05-24 06:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_alter_workevents_record_datas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workevents',
            name='record_datas',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=1),
            preserve_default=False,
        ),
    ]
