# Generated by Django 3.2.5 on 2022-02-17 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0010_auto_20220214_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoiceuploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_type', models.CharField(choices=[('*', '*'), ('APF', 'APF'), ('RF', 'RF'), ('DF', 'DF')], default='*', max_length=15)),
                ('invoices', models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='workflowitems',
            name='stage',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('AWAITING_APPROVAL', 'AWAITING_APPROVAL'), ('AWAITING_ACCEPTANCE', 'AWAITING_ACCEPTANCE'), ('ACCEPTED', 'ACCEPTED'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('FINANCE_REQUESTED', 'FINANCE_REQUESTED'), ('FINANCED', 'FINANCED'), ('FINANCE_REJECTED', 'FINANCE_REJECTED'), ('SETTLED', 'SETTLED'), ('OVERDUE', 'OVERDUE'), ('AWAITING_SIGN_A', 'AWAITING_SIGN_A'), ('AWAITING_SIGN_B', 'AWAITING_SIGN_B'), ('AWAITING_SIGN_C', 'AWAITING_SIGN_C'), ('DELETED', 'DELETED'), ('SIGN_A', 'SIGN_A'), ('SIGN_B', 'SIGN_B'), ('SIGN_C', 'SIGN_C'), ('SUBMIT', 'SUBMIT'), ('MAKER', 'MAKER'), ('NONE', 'NONE'), ('COMPLETED', 'COMPLETED')], max_length=255),
        ),
        migrations.DeleteModel(
            name='invoice_uploads',
        ),
        migrations.AddField(
            model_name='workflowitems',
            name='uploads',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.invoiceuploads'),
        ),
    ]
