# Generated by Django 3.2.5 on 2022-02-18 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0011_auto_20220217_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowitems',
            name='stage',
        ),
    ]
