# Generated by Django 3.2.5 on 2022-02-21 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction', '0012_remove_workflowitems_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='workevents',
            name='record_datas',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workevents',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
            preserve_default=False,
        ),
    ]
