# Generated by Django 3.2.5 on 2022-06-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0013_auto_20220608_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=55)),
            ],
            options={
                'verbose_name_plural': 'InterestChoice',
            },
        ),
        migrations.CreateModel(
            name='InterestRateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=55)),
            ],
            options={
                'verbose_name_plural': 'InterestRateType',
            },
        ),
    ]
