# Generated by Django 3.2.5 on 2022-02-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0013_auto_20220221_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='workevents',
            name='end',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
