# Generated by Django 3.2.5 on 2022-06-10 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0014_interestchoice_interestratetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairings',
            name='interest_rate_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transaction.interestratetype'),
        ),
        migrations.AlterField(
            model_name='pairings',
            name='interest_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='transaction.interestchoice'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programs',
            name='interest_rate_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='transaction.interestratetype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programs',
            name='interest_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='transaction.interestchoice'),
            preserve_default=False,
        ),
    ]
