# Generated by Django 3.2.5 on 2022-02-21 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0014_workevents_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowitems',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.workevents'),
        ),
    ]
