# Generated by Django 3.2.5 on 2022-02-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0015_workflowitems_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='comments',
            field=models.CharField(default=1, max_length=155),
            preserve_default=False,
        ),
    ]
