# Generated by Django 3.2.5 on 2022-03-02 08:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_models'),
        ('transaction', '0017_workevents_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='bank_loan_id',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='finance_currency_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='financedinvoicecurrency', to='accounts.currencies'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='financed_amount',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='funding_req_type',
            field=models.CharField(blank=True, choices=[('AUTOMATIC', 'AUTOMATIC'), ('ON_REQUEST', 'ON_REQUEST')], default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='invoice_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoicecurrencytype', to='accounts.currencies'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='issue_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='pairing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transaction.pairings'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.parties'),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='settlement_currency_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.currencies'),
        ),
    ]
