# Generated by Django 3.2.5 on 2022-03-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0018_auto_20220302_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='program_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
