# Generated by Django 3.2.5 on 2022-04-13 06:31

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(max_length=16, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_supervisor', models.BooleanField(default=False)),
                ('is_administrator', models.BooleanField(default=False)),
                ('is_master_admin', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=55)),
                ('bank', models.BooleanField(blank=True, default=False, null=True)),
                ('customer', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('address_line_1', models.CharField(max_length=30)),
                ('address_line_2', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=35)),
                ('state', models.CharField(max_length=35)),
                ('zipcode', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso', models.IntegerField()),
                ('description', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=155)),
                ('api_route', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Parties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=18)),
                ('name', models.CharField(max_length=35)),
                ('address_line_1', models.CharField(max_length=35)),
                ('address_line_2', models.CharField(max_length=35)),
                ('city', models.CharField(max_length=35)),
                ('state', models.CharField(max_length=35)),
                ('zipcode', models.CharField(max_length=6)),
                ('onboarded', models.BooleanField(default=False)),
                ('party_type', models.CharField(choices=[('CUSTOMER', 'CUSTOMER'), ('BANK', 'BANK'), ('OTHER', 'OTHER'), ('SELLER', 'SELLER'), ('BUYER', 'BUYER')], max_length=25)),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.currencies')),
                ('country_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.countries')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=16)),
                ('otp', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='userprocessauth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=55)),
                ('data_entry', models.BooleanField(blank=True, default=False, null=True)),
                ('sign_a', models.BooleanField(blank=True, default=False, null=True)),
                ('sign_b', models.BooleanField(blank=True, default=False, null=True)),
                ('sign_c', models.BooleanField(blank=True, default=False, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.action')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='signatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=55)),
                ('sign_a', models.BooleanField(blank=True, default=False, null=True)),
                ('sign_b', models.BooleanField(blank=True, default=False, null=True)),
                ('sign_c', models.BooleanField(blank=True, default=False, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.action')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.parties')),
            ],
        ),
        migrations.CreateModel(
            name='Partyaccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=34)),
                ('account_with_bank', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.banks')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.currencies')),
                ('party_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.parties')),
            ],
        ),
        migrations.AddField(
            model_name='banks',
            name='country_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.countries'),
        ),
        migrations.AddField(
            model_name='user',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.parties'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='signatures',
            index=models.Index(fields=['id'], name='accounts_si_id_c21b2b_idx'),
        ),
        migrations.AddIndex(
            model_name='signatures',
            index=models.Index(fields=['model'], name='accounts_si_model_f4a2f2_idx'),
        ),
        migrations.AddIndex(
            model_name='signatures',
            index=models.Index(fields=['action'], name='accounts_si_action__2ad824_idx'),
        ),
        migrations.AddIndex(
            model_name='signatures',
            index=models.Index(fields=['party'], name='accounts_si_party_i_30c476_idx'),
        ),
    ]
