# Generated by Django 3.2.5 on 2022-05-20 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name_plural': 'Action'},
        ),
        migrations.AlterModelOptions(
            name='banks',
            options={'verbose_name_plural': 'Bank'},
        ),
        migrations.AlterModelOptions(
            name='countries',
            options={'verbose_name_plural': 'Country'},
        ),
        migrations.AlterModelOptions(
            name='currencies',
            options={'verbose_name_plural': 'Currency'},
        ),
        migrations.AlterModelOptions(
            name='models',
            options={'verbose_name_plural': 'Model'},
        ),
        migrations.AlterModelOptions(
            name='parties',
            options={'verbose_name_plural': 'Party'},
        ),
        migrations.AlterModelOptions(
            name='partyaccounts',
            options={'verbose_name_plural': 'PartyAccounts'},
        ),
        migrations.AlterModelOptions(
            name='signatures',
            options={'verbose_name_plural': 'Signatures'},
        ),
        migrations.AlterModelOptions(
            name='userprocessauth',
            options={'verbose_name_plural': 'userprocessauth'},
        ),
        migrations.RemoveIndex(
            model_name='signatures',
            name='accounts_si_id_c21b2b_idx',
        ),
        migrations.RemoveIndex(
            model_name='signatures',
            name='accounts_si_model_f4a2f2_idx',
        ),
        migrations.RemoveIndex(
            model_name='signatures',
            name='accounts_si_action__2ad824_idx',
        ),
        migrations.RemoveIndex(
            model_name='signatures',
            name='accounts_si_party_i_30c476_idx',
        ),
    ]
