# Generated by Django 3.2.5 on 2022-02-09 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_maker',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_sign_a',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_sign_b',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_sign_c',
        ),
        migrations.AlterField(
            model_name='userprocessauth',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
