# Generated by Django 3.2.5 on 2022-05-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220520_1840'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='signatures',
            index=models.Index(fields=['id'], name='accounts_si_id_c21b2b_idx'),
        ),
        migrations.AddIndex(
            model_name='signatures',
            index=models.Index(fields=['model'], name='accounts_si_model_f4a2f2_idx'),
        ),
        migrations.AddIndex(
            model_name='signatures',
            index=models.Index(fields=['action'], name='accounts_si_action__2ad824_idx'),
        ),
        migrations.AddIndex(
            model_name='signatures',
            index=models.Index(fields=['party'], name='accounts_si_party_i_30c476_idx'),
        ),
    ]
