# Generated by Django 3.2.5 on 2022-02-11 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprocessauth_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprocessauth',
            old_name='model_id',
            new_name='model',
        ),
    ]
