# Generated by Django 3.2.5 on 2022-02-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_model_id_userprocessauth_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parties',
            name='party_type',
            field=models.CharField(choices=[('CUSTOMER', 'CUSTOMER'), ('BANK', 'BANK'), ('OTHER', 'OTHER'), ('SELLER', 'SELLER'), ('BUYER', 'BUYER')], max_length=25),
        ),
    ]
