# Generated by Django 3.2.5 on 2022-06-08 05:13

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_parties_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.FileField(default=1, upload_to=accounts.models.profile_img_path),
            preserve_default=False,
        ),
    ]
