# Generated by Django 3.2.5 on 2022-06-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencies',
            name='dial_code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currencies',
            name='iso',
            field=models.IntegerField(unique=True),
        ),
    ]
