# Generated by Django 3.2.5 on 2022-02-11 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_parties_party_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=55)),
                ('bank', models.BooleanField(blank=True, default=False, null=True)),
                ('customer', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='signatures',
            name='accounts_si_action_90a8e4_idx',
        ),
        migrations.AddIndex(
            model_name='signatures',
            index=models.Index(fields=['action'], name='accounts_si_action__2ad824_idx'),
        ),
        migrations.AlterField(
            model_name='signatures',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.action'),
        ),
        migrations.AlterField(
            model_name='userprocessauth',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.action'),
        ),
    ]
