# Generated by Django 3.2.5 on 2022-06-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_currencies_iso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencies',
            name='dial_code',
        ),
        migrations.AddField(
            model_name='countries',
            name='dial_code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
