# Generated by Django 3.2.5 on 2022-03-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_master_admin',
            field=models.BooleanField(default=False),
        ),
    ]
